name: Java CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃 (변경 없음)
      - name: Checkout
        uses: actions/checkout@v3

      # 2. JDK 17 설치 (변경 없음)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 실행 권한 부여 (작업 위치 변경)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend

      # 4. Gradle로 빌드 (작업 위치 변경)
      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./backend

      # 5. Docker Hub 로그인 (변경 없음)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 6. Docker 이미지 빌드 및 Push (컨텍스트 경로 변경)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend # <--- 경로를 './backend'로 수정
          push: true
          tags: kbosung/study-app:latest

      # 7. EC2에 접속하여 배포 (변경 없음)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -f